service: dexscan-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  vpc:
    securityGroupIds:
      - sg-029df8e48faf39ec5
    subnetIds:
      - subnet-0ba99baf55334aa37
      - subnet-0e2f1f8fb76211642
      - subnet-040dc7170e0e988f0
      - subnet-061925e9b651a9fd1
  environment:
    TOKENS_TABLE: tokens-table
    PGHOST: ${param:PGHOST}
    PGUSER: ${param:PGUSER}
    PGDATABASE: ${param:PGDATABASE}
    PGPASSWORD: ${param:PGPASSWORD}
    PGPORT: 5432
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
    - Effect: Allow
      Action:
        - rds-db:connect
      Resource: arn:aws:rds:us-east-1:283169336544:db-proxy:prx-0b51bb42d90f6a22f

functions:
  allTokenUpdateHandler:
    handler: handler.allTokenUpdateHandler
    events:
      # Invoke Lambda function every minute
      - schedule: 
          rate: rate(5 minutes)  
  kdaPriceUpdateHandler:
    handler: handler.kdaPriceUpdateHandler
    events:
      # Invoke Lambda function every minute
      - schedule: 
          rate: rate(1 minute)  
  candleUpdateHandler:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
  candleUpdateHandlerTwo:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
  hourCandlesUpdateHandler:
    handler: handler.hourCandlesUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
  highLowUpdateHandler:
    handler: handler.highLowUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)

package:
  patterns:
    - '!scripts/**'

resources:
  Resources:
    cacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tokens-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST